# Generated by Django 3.0.14 on 2022-12-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_ime', models.CharField(max_length=30)),
                ('mentor_prezime', models.CharField(max_length=30)),
                ('mentor_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
