# Generated by Django 3.0.14 on 2022-12-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ime', models.CharField(max_length=25)),
                ('student_prezime', models.CharField(max_length=50)),
                ('student_broj_xice', models.CharField(max_length=10)),
            ],
        ),
    ]
