# Generated by Django 3.0.14 on 2022-12-11 15:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kolegij',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolegij_naziv', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ZavrsniRad',
            fields=[
                ('student', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Student')),
                ('zavrsni_naslov', models.CharField(max_length=50)),
                ('zavrsni_broj_prijave', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('mentor', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Mentor')),
                ('zavrsni_kolegij', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Kolegij')),
            ],
        ),
    ]
