# Generated by Django 4.1.4 on 2022-12-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_kolegij_zavrsnirad'),
    ]

    operations = [
        migrations.AddField(
            model_name='kolegij',
            name='kolegij_nositelj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.mentor'),
        ),
    ]
