# Generated by Django 4.1.4 on 2022-12-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_student_student_kolegiji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zavrsnirad',
            old_name='mentor',
            new_name='zavrsni_mentor',
        ),
        migrations.RenameField(
            model_name='zavrsnirad',
            old_name='student',
            new_name='zavrsni_student',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='mentor_email',
        ),
    ]
